fix issue, then it wasn't possible to view FBD programs
the reason for that is possible wx-3.0-gtk2 bug that happens if
ALWAYS_SHOW_SB is set.

Traceback (most recent call last):
  File "Beremiz.py", line 1045, in OnProjectTreeItemActivated
    IDEFrame.OnProjectTreeItemActivated(self, event)
  File "IDEFrame.py", line 1667, in OnProjectTreeItemActivated
    self.EditProjectElement(item_infos["type"], item_infos["tagname"])
  File "IDEFrame.py", line 1752, in EditProjectElement
    new_window = Viewer(self.TabsOpened, tagname, self, self.Controler)
  File "editors/Viewer.py", line 611, in __init__
    EditorPanel.__init__(self, parent, tagname, window, controler, debug)
  File "editors/EditorPanel.py", line 68, in __init__
    self._init_ctrls(parent)
  File "editors/EditorPanel.py", line 52, in _init_ctrls
    self._init_Editor(self)
  File "editors/Viewer.py", line 603, in _init_Editor
    style=wx.HSCROLL | wx.VSCROLL | wx.ALWAYS_SHOW_SB)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_windows.py", line 296, in __init__
    _windows_.ScrolledWindow_swiginit(self,_windows_.new_ScrolledWindow(*args, **kwargs))
PyAssertionError: C++ assertion "scrolled" failed at ../src/gtk/scrolwin.cpp(205) in DoShowScrollbars(): window must be created